// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhlfdefjpmkoluwxqmxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxobGZkZWZqcG1rb2x1d3hxbXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTg1NzIsImV4cCI6MjA3MTY5NDU3Mn0.Q_oN3q2yDY2fVrYRICZjCQdIZgL1AbHjocOh7_JzWCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});